//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public int DiemID { get; set; }
        public int HocSinhID { get; set; }
        public int MonHocID { get; set; }
        public Nullable<double> Diem15p { get; set; }
        public Nullable<double> DiemGK { get; set; }
        public Nullable<double> DiemCK { get; set; }
        public Nullable<double> DiemTB { get; set; }
        public int HocKyID { get; set; }
        public int NamHocID { get; set; }
        public Nullable<double> DiemMieng { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual HocSinh HocSinh { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual NamHoc NamHoc { get; set; }
    }
}
