//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocKy
    {
        public HocKy()
        {
            this.Diem = new HashSet<Diem>();
            this.KetQuaHocTap = new HashSet<KetQuaHocTap>();
            this.ThoiKhoaBieu = new HashSet<ThoiKhoaBieu>();
        }
    
        public int HocKyID { get; set; }
        public string TenHocKy { get; set; }
        public int NamHocID { get; set; }
    
        public virtual ICollection<Diem> Diem { get; set; }
        public virtual NamHoc NamHoc { get; set; }
        public virtual ICollection<KetQuaHocTap> KetQuaHocTap { get; set; }
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
    }
}
