//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh_PhuHuynh
    {
        public int HocSinhID { get; set; }
        public int PhuHuynhID { get; set; }
        public string VaiTroTrongGiaDinh { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual PhuHuynh PhuHuynh { get; set; }
    }
}
