//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        public HocSinh()
        {
            this.Diem = new HashSet<Diem>();
            this.HocSinh_PhuHuynh = new HashSet<HocSinh_PhuHuynh>();
            this.KetQuaHocTap = new HashSet<KetQuaHocTap>();
        }
    
        public int HocSinhID { get; set; }
        public int NguoiDungID { get; set; }
        public int LopHocID { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string TinhThanhPho { get; set; }
        public string QuanHuyen { get; set; }
        public string DiaChiNha { get; set; }
        public string CCCD { get; set; }
        public string DanToc { get; set; }
        public string TrangThaiHocTap { get; set; }
    
        public virtual ICollection<Diem> Diem { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ICollection<HocSinh_PhuHuynh> HocSinh_PhuHuynh { get; set; }
        public virtual ICollection<KetQuaHocTap> KetQuaHocTap { get; set; }
    }
}
