//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaHocTap
    {
        public int KetQuaID { get; set; }
        public int HocSinhID { get; set; }
        public int HocKyID { get; set; }
        public int NamHocID { get; set; }
        public Nullable<double> DTBTong { get; set; }
        public string HocLuc { get; set; }
        public string HanhKiem { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual HocSinh HocSinh { get; set; }
        public virtual NamHoc NamHoc { get; set; }
    }
}
