//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoiLop
    {
        public KhoiLop()
        {
            this.LopHoc = new HashSet<LopHoc>();
        }
    
        public int KhoiLopID { get; set; }
        public string TenKhoi { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<LopHoc> LopHoc { get; set; }
    }
}
