//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        public MonHoc()
        {
            this.Diem = new HashSet<Diem>();
            this.GiaoVien = new HashSet<GiaoVien>();
            this.ThoiKhoaBieu = new HashSet<ThoiKhoaBieu>();
        }
    
        public int MonHocID { get; set; }
        public string TenMonHoc { get; set; }
        public string ApDungKhoi { get; set; }
        public string TrangThaiMonHoc { get; set; }
        public int BoMonID { get; set; }
        public int SoTietToiDaTrongNam { get; set; }
    
        public virtual BoMon BoMon { get; set; }
        public virtual ICollection<Diem> Diem { get; set; }
        public virtual ICollection<GiaoVien> GiaoVien { get; set; }
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
    }
}
