//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamHoc
    {
        public NamHoc()
        {
            this.Diem = new HashSet<Diem>();
            this.HocKy = new HashSet<HocKy>();
            this.KetQuaHocTap = new HashSet<KetQuaHocTap>();
            this.LopHoc = new HashSet<LopHoc>();
            this.ThoiKhoaBieu = new HashSet<ThoiKhoaBieu>();
        }
    
        public int NamHocID { get; set; }
        public string TenNamHoc { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<Diem> Diem { get; set; }
        public virtual ICollection<HocKy> HocKy { get; set; }
        public virtual ICollection<KetQuaHocTap> KetQuaHocTap { get; set; }
        public virtual ICollection<LopHoc> LopHoc { get; set; }
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
    }
}
