//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.GiaoVien = new HashSet<GiaoVien>();
            this.HocSinh = new HashSet<HocSinh>();
            this.ThongBao = new HashSet<ThongBao>();
            this.ThongBaoDaDoc = new HashSet<ThongBaoDaDoc>();
        }
    
        public int NguoiDungID { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string VaiTro { get; set; }
        public string TrangThaiTK { get; set; }
        public string AnhDaiDien { get; set; }
        public string ResetToken { get; set; }
        public Nullable<System.DateTime> ResetTokenExpiry { get; set; }
    
        public virtual ICollection<GiaoVien> GiaoVien { get; set; }
        public virtual ICollection<HocSinh> HocSinh { get; set; }
        public virtual ICollection<ThongBao> ThongBao { get; set; }
        public virtual ICollection<ThongBaoDaDoc> ThongBaoDaDoc { get; set; }
    }
}
