//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongHoc
    {
        public PhongHoc()
        {
            this.ThoiKhoaBieu = new HashSet<ThoiKhoaBieu>();
        }
    
        public int PhongHocID { get; set; }
        public string TenPhong { get; set; }
        public string LoaiPhong { get; set; }
        public Nullable<int> SoLuongChoNgoi { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
    }
}
