//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuHuynh
    {
        public PhuHuynh()
        {
            this.HocSinh_PhuHuynh = new HashSet<HocSinh_PhuHuynh>();
        }
    
        public int PhuHuynhID { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string NgheNghiep { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        public virtual ICollection<HocSinh_PhuHuynh> HocSinh_PhuHuynh { get; set; }
    }
}
