//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTruongHocEntities : DbContext
    {
        public QuanLyTruongHocEntities()
            : base("name=QuanLyTruongHocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BoMon> BoMon { get; set; }
        public DbSet<Diem> Diem { get; set; }
        public DbSet<GiaoVien> GiaoVien { get; set; }
        public DbSet<HocKy> HocKy { get; set; }
        public DbSet<HocSinh> HocSinh { get; set; }
        public DbSet<HocSinh_PhuHuynh> HocSinh_PhuHuynh { get; set; }
        public DbSet<KetQuaHocTap> KetQuaHocTap { get; set; }
        public DbSet<KhoiLop> KhoiLop { get; set; }
        public DbSet<LopHoc> LopHoc { get; set; }
        public DbSet<MonHoc> MonHoc { get; set; }
        public DbSet<NamHoc> NamHoc { get; set; }
        public DbSet<NguoiDung> NguoiDung { get; set; }
        public DbSet<PhongHoc> PhongHoc { get; set; }
        public DbSet<PhuHuynh> PhuHuynh { get; set; }
        public DbSet<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
        public DbSet<ThongBao> ThongBao { get; set; }
        public DbSet<ThongBaoDaDoc> ThongBaoDaDoc { get; set; }
    }
}
