//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieu
    {
        public int TKBID { get; set; }
        public string Thu { get; set; }
        public string TietHoc { get; set; }
        public int MonHocID { get; set; }
        public int GiaoVienID { get; set; }
        public int LopHocID { get; set; }
        public int PhongHocID { get; set; }
        public int HocKyID { get; set; }
        public int NamHocID { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocKy HocKy { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual NamHoc NamHoc { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
    }
}
