//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBaoDaDoc
    {
        public int ThongBaoDaDocID { get; set; }
        public int ThongBaoID { get; set; }
        public int NguoiDungID { get; set; }
        public System.DateTime NgayDoc { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ThongBao ThongBao { get; set; }
    }
}
