//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public ThongBao()
        {
            this.ThongBaoDaDoc = new HashSet<ThongBaoDaDoc>();
        }
    
        public int ThongBaoID { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayThongBao { get; set; }
        public bool GuiChoHocSinh { get; set; }
        public bool GuiChoGiaoVien { get; set; }
        public int NguoiTaoID { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayKetThucTB { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ICollection<ThongBaoDaDoc> ThongBaoDaDoc { get; set; }
    }
}
